### ISSUE TITLE
Add Windows support for Travis

### ISSUE THREAD

**Issue by acharaakshit** [acharaakshit/RMiniZinc#1]
R for Windows is not supported by Travis. So, R should be installed and set up manually by scripting it properly in travis.yml. MiniZinc should also be installed and added to path once R is installed.

**Comment by acharaakshit** [comment]
In travis.yml, the exe for MiniZinc gets downloaded using wget and then when the PowerShell command to install the exe silently gets executed, no output is received for 10 minutes which indicates a stalled build.

**Comment by larskotthoff** [comment]
Thanks -- if this turns out to be a pain, it's also ok to just do Linux for now.

**Comment by acharaakshit** [comment]
Sure, I will try to figure out the fix for this and if it takes too long then I will come back to this later. Currently the builds for Linux and OS X  are working. Thanks!

**Comment by acharaakshit** [comment]
I have removed the windows tests from Travis for now. I will come back to this towards the end if required.
