### ISSUE TITLE
[Feature request] Chuffed free search setting functionality 

### ISSUE THREAD

**Issue by ben-phillips1** [acharaakshit/RMiniZinc#57]
Hi Akshit,

I am wondering if there is any way to implement the free search flag when calling chuffed using mzn_eval?

e.g.  in this situation:

`solv_obj<- rminizinc::mzn_eval(parse_obj, solver = "Chuffed",
                              lib_path = paste0("/path/to/minizinc"),
                              all_solutions = TRUE, time_limit = 30000)`

I can see that the flags for chuffed are present in the 'chuffed.msc.in' file. Would it work by adding the -f flag somewhere in the mzn_eval.cpp file? 

Thanks a lot for your help with this and please let me know if you would need any more details. 

Best wishes,
Ben

**Comment by acharaakshit** [comment]
Hi Ben,

Only a few options like `solver`, `all_solutions` and `time_limit` were provided in the latest release. In the latest commit in the development branch, I have added an option to provide other minizinc command line options required for solving problems through the argument `other_cl_options` in `mzn_eval()`. You can supply multiple command line options to get a suitable solution. 

You can install the development version using :
`devtools::install_github(repo = "acharaakshit/RMiniZinc", ref = "development", configure.args="--with-mzn=/path/to/libminizinc --with-bin=/path/to/solver/bin", force = TRUE)`
 
An example use in your case would be:
`solv_obj<- rminizinc::mzn_eval(parse_obj, solver = "Chuffed", lib_path = paste0("/path/to/minizinc"), all_solutions = TRUE, time_limit = 30000, other_cl_options = c("-f"))`

Please let me know if this option works fine for you and if you are able to use other options according to your needs.

Thanks,
Akshit

**Comment by ben-phillips1** [comment]
Amazing, works great. Thanks Akshit.

Cheers,
Ben

**Comment by acharaakshit** [comment]
Thanks Ben, I will make this change in the next CRAN release.
